@startuml

class Company {
    - _id: int
    - _name: String
    --
    # Company(name: String)
    + getId(): int
    /'Here we need to give the array of products to later use the
      recommended price of each of the products '/
    + getSellPrice(inventory: Inventory): Product[]
}


/'An inventory is the logical relation between a company'/
class Inventory {
    - _availableUnits: int
    - _multipliedFactor: double
    --
    # Inventory(availableUnits: int, multipliedFactor: double)
    + changeInventory(num: int, newFactor: double): int
}

/'One company asks for 0 till infinite ammounts of products and
  one product can ask for 0 till infinite ammount of inventory items'/
Company "1" -- "0..*" Inventory
Product "1" -- "0..*" Inventory

@enduml
