@startuml

class Product {
    - _id: int
    - _name: String
    - _description: String
    - _basePrice: int
    - _category: String
    - _deliveryTerm: int
    - _provenance: Provenance
    --
    # Product(name: String, description: String, category: String,
              deliveryTerm: int, basePrice: int, provenance: Provenance)
    + getId(): int
    + getRecommendedPrice(totalUnits: int): double
}


/' Correlation between the provenance of a product, abstract class because
   it declares a following pattern for its subclasses '/
abstract class Provenance {
    + calculateRecommendedPrice(basePrice: int, totalUnits: int): double
}


/' Subclass of provenance '/
class NationalProduct {
    + calculateRecommendedPrice(basePrice: int, totalUnits: int): double
}


/' Subclass of provenance '/
class ImportedProduct {
    - _originCountry: String
    - _customsTax: double
    --
    + calculateRecommendedPrice(basePrice: int, totalUnits: int): double
}


class Company {
    - _id: int
    - _name: String
    --
    # Company(name: String)
    + getId(): int
    /'Here we need to give the array of products to later use the
      recommended price of each of the products '/
    + getSellPrice(inventory: Inventory): Product[]
}


/'An inventory is the logical relation between a company'/
class Inventory {
    - _availableUnits: int
    - _multipliedFactor: double
    --
    # Inventory(availableUnits: int, multipliedFactor: double)
    + changeInventory(num: int, newFactor: double): int
    + notify(n:Notification):void
}


class Client {
    - _mechanism:NotificationMechanism
    - _name: String
    - _email: String
    --
    # Client(name: String, email: String)
    + getName(): String
}


/' Handles the logic behind the transitioning in a company
   and a client for the different items '/
class ShoppingBucket {
    - _items: Item[]
    - _divisionStrategy: OrderDivisionStrategy
    - _transportMode: TransportMode
    - _extraService: ExtraService[]
    --
    + addProduct(product: Product, quantity: int): boolean
    + changeQuantity(product: Product, quantity: int): boolean
    + removeProduct(product: Product): boolean
    + isEmpty(): boolean

    + chooseDivisionStrategy(strategy: OrderDivisionStrategy)
    + chooseTransportMode(mode: TransportMode)
    + addExtraService(service: ExtraService)
    + removeExtraService(service: ExtraService)
}


/' An item can be inside a ShoppingBucket '/
class Item {
    - _product: Product
    - _quantity: int
    --
    + changeQuantity(quantity: int): boolean
}


/'One company asks for 0 till infinite ammounts of products and
  one product can ask for 0 till infinite ammount of inventory items'/
Company "1" -- "0..*" Inventory
Product "1" -- "0..*" Inventory


/' Each product has its own provenance and it inherits from product '/
Product "1" *-- "1" Provenance


/' Being a characterists, they inherit from provenance '/
NationalProduct --|> Provenance
ImportedProduct --|> Provenance


/' Each company and client can only have one shopping bucket
   each shopping bucket can be connected to each of characteristics '/
Client "1" -- "0..*" ShoppingBucket
Company "1" -- "0..*" ShoppingBucket
ShoppingBucket "0..1" --> "1" OrderDivisionStrategy
ShoppingBucket "0..1" --> "1" TransportMode

/' agregation relation, ExtraService can exist without ShoppingBucket
   like a whole-part logic for this context '/
ShoppingBucket "1" o-- "0..*" ExtraService


/' There can be multiple items associated to one product only
   and each shopping bucket can have any amount of a specific item '/
ShoppingBucket "1" *-- "0..*" Item
Item "0..*" --> "1" Product


class Purchase {
    - _id:int
    - _client:Client
    - _company:Company
    - _date:int
    - _lines:[PurchaseLine]
    - _orders:[Order]
    --
    # Purchase(int id, Client client, Company company, int date, [PurchaseLine] lines)
    + productsCost():double
    + ordersCost():double
    + totalCost():double
}
Purchase "*" --> "1" Client
Purchase "*" --> "1" Company
Purchase "1" *-- "1..*" PurchaseLine 
' I had "1" --> "1..*" PurchaseLine but it would be more correct for *-- because
' a purchase can have many lines and a line belongs to only one purchase but I'm not sure
Purchase "1" --> "1..*" Order


class PurchaseLine {
    - _product:Product
    - _quantity:int
    - _unitPrice:double
    --
    # PurchaseLine(Product product, int quantity, double unitPrice)
    + cost():double
}
PurchaseLine "*" --> "1" Product


class Order {
    - _purchase:Purchase
    - _lines:[PurchaseLine]
    - _modality:Modality
    - _services:[Service]
    - _delivered:boolean
    --
    # Order(Purchase purchase, [PurchaseLine] lines, Modality modality, [Service] services)
    + baseDelay():int
    + linesValue():double
    + processingCost():double
    + cost(): double
    + expectedDeliveryDate():int     
    + isDelivered():boolean
    + markDelivered():void
    + transportDescription():String
}
Order "*" --> "1" Purchase
Order "1" o-- "1..*" PurchaseLine
Order "*" --> "1" Modality
Order "*" --> "0..*" Service


' Dictates the interface for the strategy pattern 
interface SplitStrategy extends Serializable {
    + key():String
    + split(lines:List<PurchaseLine>):List<List<PurchaseLine>>
}
class SingleOrderStrategy
class DelayGroupingStrategy
SingleOrderStrategy ..|> SplitStrategy
DelayGroupingStrategy ..|> SplitStrategy


interface Service extends Serializable {
    + key():String
    + cost():int
    + extraDays():int
}
class Wrapping
class GiftCard
Wrapping ..|> Service
GiftCard ..|> Service


class Modality {
    - _name:String
    - _tariff:int
    - _days:int
    --
    # Modality(String name, int tariff, int days)
}

' Order.expectedDeliveryDate():int
 ' purchase.date() + baseDelay() + modality.days() + soma(service.extraDays()) 


' isDelivered(int currentDate):boolean
 ' currentDate >= expectedDeliveryDate()


' Express Retail Plataform
class Erp { 
    - _date:int
    - _nextProductId:int
    - _nextCompanyId:int
    - _nextPurchaseId:int
    - _modified:boolean
    --
    + currentDate():int
    + advanceDate(days:int):void
}
Erp ..> Order
Erp ..> Client
Erp "1" --> "*" Company
Erp "1" --> "*" Product
Erp "1" --> "*" Client
Erp "1" --> "*" Modality
Erp "1" --> "*" SplitStrategy


class Notification {
    - _subject:String
    - _description:String
    --
    + toString():String
}


interface NotificationMechanism extends Serializable {
    + deliver(n:Notification):void
}
NotificationMechanism ..> Notification


class DefaultNotification {
    - _notifications:List<Notification>
    --
    + deliver(n:Notification):void
    + collect():List<Notification>
}
DefaultNotification ..|> NotificationMechanism

/'
' Client class from 1.3, needs to have attribute "_mechanism" and method "notify"
class Client {
    - _mechanism:NotificationMechanism
    --
    + notify(n:Notification):void
}
'/
Client "*" --> "1" NotificationMechanism
' Previously I had Client ..> DefaultNotification but I erased it, it would be wrong right?
Client ..> Notification


/' 
Changes to Order class from 1.5
class Order {
    - _delivered:boolean
    --
    + isDelivered():boolean
    + markDelivered():void
}
Order "*" --> "1" Purchase
'/


/' 
Changes to Erp class from 1.7
class Erp { 
    - _nextProductId:int
    - _nextCompanyId:int
    - _nextPurchaseId:int
    --
}
'/
@enduml
