@startuml

class Product {
    - _id: int
    - _name: String
    - _description: String
    - _basePrice: int
    - _category: String
    - _deliveryTerm: int
    - _provenance: Provenance
    --
    # Product(name: String, description: String, category: String,
              deliveryTerm: int, basePrice: int, provenance: Provenance)
    + getId(): int
    + getRecommendedPrice(totalUnits: int): double
}
Product "1" *-- "1" Provenance


/' Correlation between the provenance of a product, abstract class because
   it declares a following pattern for its subclasses '/
abstract class Provenance {
    + calculateRecommendedPrice(basePrice: int, totalUnits: int): double
}


/' Subclass of provenance '/
class NationalProduct {
    + calculateRecommendedPrice(basePrice: int, totalUnits: int): double
}
NationalProduct --|> Provenance


/' Subclass of provenance '/
class ImportedProduct {
    - _originCountry: String
    - _customsTax: double
    --
    + calculateRecommendedPrice(basePrice: int, totalUnits: int): double
}
ImportedProduct --|> Provenance

@enduml
