@startuml

class ShoppingBucket {
    - _items: Item[]
    - _divisionStrategy: OrderDivisionStrategy
    - _transportMode: TransportMode
    - _extraService: ExtraService[]
    --
    + addProduct(product: Product, quantity: int): boolean
    + changeQuantity(product: Product, quantity: int): boolean
    + removeProduct(product: Product): boolean
    + isEmpty(): boolean

    + chooseDivisionStrategy(strategy: OrderDivisionStrategy)
    + chooseTransportMode(mode: TransportMode)
    + addExtraService(service: ExtraService)
    + removeExtraService(service: ExtraService)
}

Client "1" -- "0..*" ShoppingBucket
Company "1" -- "0..*" ShoppingBucket

ShoppingBucket "0..1" --> "1" OrderDivisionStrategy
ShoppingBucket "0..1" --> "1" TransportMode
ShoppingBucket "1" o-- "0..*" ExtraService

class Item {
    - _product: Product
    - _quantity: int
    --
    + changeQuantity(quantity: int): boolean
}

ShoppingBucket "1" *-- "0..*" Item
Item "0..*" --> "1" Product

@enduml
